# Generated by Django 3.1.2 on 2020-10-06 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GioiTinh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenGioiTinh', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ThongTin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('XuatXu', models.CharField(default='', max_length=255)),
                ('May', models.CharField(default='', max_length=255)),
                ('BaoHang', models.CharField(default='', max_length=255)),
                ('DayDeo', models.CharField(default='', max_length=255)),
                ('ChongNuoc', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ThuongHieu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenThuongHieu', models.CharField(default='', max_length=255)),
                ('MoTa', models.TextField(default='')),
                ('Anh', models.ImageField(upload_to='', verbose_name='tra_pictures ')),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenSanPham', models.CharField(default='', max_length=255)),
                ('MoTa', models.TextField(default='')),
                ('SanPham_GiamGia', models.BooleanField(default=False)),
                ('SanPham_Hot', models.BooleanField(default=False)),
                ('Gia', models.IntegerField(default=0)),
                ('Gia_Giam', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('GioiTinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.gioitinh')),
                ('ThongTin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.thongtin')),
                ('ThuongHieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.thuonghieu')),
            ],
        ),
    ]
