# Generated by Django 3.1.2 on 2020-10-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thongtin',
            old_name='BaoHang',
            new_name='BaoHanh',
        ),
        migrations.AddField(
            model_name='thongtin',
            name='DuongKinh',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='thongtin',
            name='MatKinh',
            field=models.CharField(default='', max_length=255),
        ),
    ]
