# Generated by Django 3.1.2 on 2020-10-17 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donhang', '0003_auto_20201017_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiaoHang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenNguoiNhan', models.CharField(default='', max_length=100)),
                ('DiaChi', models.CharField(default='', max_length=100)),
                ('SoDienThoai', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
