# Generated by Django 3.1.2 on 2020-10-17 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donhang', '0005_auto_20201017_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='giaohang',
            name='DonHang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donhang.donhang'),
        ),
    ]
