# Generated by Django 3.1.2 on 2020-10-24 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0002_auto_20201017_0958'),
        ('donhang', '0006_auto_20201017_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiTietDon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoLuong', models.IntegerField(default=0)),
                ('Don', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donhang.donhang')),
                ('SanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.sanpham')),
            ],
        ),
    ]
