# Generated by Django 3.1.2 on 2020-10-29 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donhang', '0007_auto_20201024_1050'),
    ]

