# Generated by Django 3.1.2 on 2020-10-06 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sanpham', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuKien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TieuDe', models.CharField(default='', max_length=255)),
                ('Anh', models.ImageField(upload_to='', verbose_name='even_picture')),
                ('TrangThai', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChiTiet_Sukien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NgayDang', models.DateField(auto_now_add=True)),
                ('SanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.sanpham')),
                ('SuKien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sukien.sukien')),
            ],
        ),
    ]
