# Generated by Django 3.1.2 on 2020-11-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sukien', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitiet_sukien',
            name='Giam',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='sukien',
            name='MoTa',
            field=models.TextField(default=''),
        ),
    ]
