# Generated by Django 3.1.2 on 2020-10-06 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sanpham', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChinhSua', models.DateField(auto_now=True)),
                ('LoaiAnh', models.IntegerField(default=0)),
                ('Anh', models.ImageField(upload_to='', verbose_name='pro_pictures ')),
                ('SanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.sanpham')),
            ],
        ),
    ]
